version: '3.8'

services:
  iot-app:
    container_name: iot-devops-app
    build:
      context: .           
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mqtt-broker
    working_dir: /app
    networks:
      - iot-net
    # You’ll override CMD or entrypoint later to run send.py or recv.py

  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge