name: iot-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - pip:
      - paho-mqtt
      - fastapi
      - uvicorn[standard]
      - python-dotenv
      - joblib
      - pytest
      - pytest-cov